### ISSUE TITLE
Anyone can help developing a LESS/SASS compile script?

### ISSUE THREAD

**Issue by thednp** [thednp/navbar.js#1]
I am now working on LESS/SASS sources and need a little bit of help, I need a `build.js` script to minify the JS and compile&minify the CSS.

Perhaps @RyanZim can you help with some suggestion?

**Comment by RyanZim** [comment]
Sorry, no experience with LESS/SASS. I'm crazy busy right now working on `fs-extra` and a few other open-source projects.

**Comment by thednp** [comment]
@RyanZim I finished the `build-less.js` and `build-js.js` tools, now heading for SCSS tools.

**Comment by thednp** [comment]
Added build tools and now closing this.
https://github.com/thednp/navbar.js/commit/3f96ae4596aaeb33c61b1c6a53a1e47d5fd1a714
