### ISSUE TITLE
Dropdown not working on focus

### ISSUE THREAD

**Issue by rafiul** [thednp/navbar.js#10]
Thanks for the nice plugin. Please give support on focus also.

**Comment by thednp** [comment]
You mean for accessibility?

**Comment by rafiul** [comment]
Actually a new requirement for the WordPress.org theme.  I solved by adding some code.

//add for focus.  line 13
  `var FucusEvents = ('focus' in document) ? [ 'focusin', 'focusout'] : [ 'focusin', 'focusout' ];`

// for focus.  line 79
	`listItem[action](FucusEvents[0], enterHandler);
         listItem[action](FucusEvents[1], leaveHandler);`

**Comment by thednp** [comment]
Will work on this as soon as I get some time.

**Comment by thednp** [comment]
I don't see a reason why we would have `fucusEvents` where they are both the same on both sides.
