### ISSUE TITLE
Dropdown issue

### ISSUE THREAD

**Issue by elemis** [thednp/navbar.js#14]
Sometimes moving outside of links breaks the dropdown (happens with all major browsers). Any way to overcome this without sacrificing transitions?

https://user-images.githubusercontent.com/608547/147064212-48771c78-afa2-4f9a-90a4-f2abf252ee04.mov

**Comment by thednp** [comment]
I can confirm the issue as the video demo is very clear. Will have a look asap.

Thank you.

**Comment by elemis** [comment]
Unfortunately the issue still remains with 3.0.4. Removing CSS transitions solves it but would like to keep them.

https://user-images.githubusercontent.com/608547/147211661-a13fddd8-d4b1-4718-959a-35d833211501.mov

**Comment by thednp** [comment]
Yea, will look into it asap and let you know asap. Thanks again

**Comment by thednp** [comment]
This is to confirm that I'm on this right now. I'm working on a solution to handle timers separately for each parent `<li>` element, it might take some time, so sit tight. I'm also open to any suggestion you might have.

**Comment by thednp** [comment]
@elemis can you please confirm the fix?

**Comment by elemis** [comment]
Thank you for taking your time. Just tested 3.0.5 and there is definitely some improvement that it's happening less now.

**Comment by thednp** [comment]
It can never happen, if you investigate the new code, I've developed a `Timer` which in Navbar uses two states (in and out) for each parent element.

**Comment by elemis** [comment]
Thank you!
