### ISSUE TITLE
Using new nav bar (and old)

### ISSUE THREAD

**Issue by vic-cekvenich** [thednp/navbar.js#19]
Hi. I'm using your new Navbar here: https://11.intuition.dev
as a starter 11ty v2.x kit.
(I have some z-index issue, but I'll fix it).

Also, I used your old lib here for a project: https://www.ubaycap.com

That is all. Thanks. I'll find a way to contribute later this year. Cheers, Vic

**Comment by thednp** [comment]
Hey be sure to check out the latest v3.2.0, Typescript sourced and updated SCSS sources.
