### ISSUE TITLE
reset ul ol

### ISSUE THREAD

**Issue by englishextra** [thednp/navbar.js#2]
Because their could be a typography rules for ul ol it's good thing to reset ol ul in navbar.css

```
.nav,
.nav ol,
.nav ul {
	list-style: none;
	padding: 0;
}
```

**Comment by thednp** [comment]
It's a good idea, but I don't see anyone using `ol` for navigation.

**Comment by englishextra** [comment]
I guess that would be fine?

```
.nav,
.nav ul {
	list-style: none;
	padding: 0;
}

.nav,
.nav ol,
.nav ul {
	margin: 0;
}
```

As for ol - yes, ```ol``` is used when numbering is needed.

**Comment by thednp** [comment]
Implemented in the next major version, not sure if `ol` is actually used in menu items IMO.

**Comment by englishextra** [comment]
@thednp thanks
