### ISSUE TITLE
Close .nav on any items tapped/clicked

### ISSUE THREAD

**Issue by englishextra** [thednp/navbar.js#3]
It is needed when you have hash links that load another content via ajax, and the menu stays opened, and we dont want that.
In short:

```
		mouseHover = ('onmouseleave' in document) ? ['mouseenter', 'mouseleave'] : ['mouseover', 'mouseout'],
		+ mouseClick = ('ontouchstart' in document) ? ['tap'] : ['click'],

...
			for (var i = 0, itemsLength = items[length]; i < itemsLength; i++) {
				if (items[i][getElementsByTagName]('UL')[length]) {
					on(items[i], mouseHover[0], enterHandler);
					on(items[i], mouseHover[1], leaveHandler);
					+ on(items[i], mouseClick[0], leaveHandler);

```

**Comment by thednp** [comment]
Ah yes I forgot about that. I will think of a good solution but it's good I have something to start with ;)

**Comment by englishextra** [comment]
onclick for top visible item with chevron down should reveal dropdown
onclick for other items should hide all dropdowns
click on body should hide all dropdowns (but it is not needed, because you have a closing  action on mouseout)

these probaby arent needed:
mouseenter should accompany the touchenter 
mouseleave should accompany the touchleave

so, perhaps:
```
		mouseHover = ('ontouchstart' in document) ? ['touchenter', 'touchleave'] : ['mouseover', 'mouseout'],
		mouseClick = ('ontouchstart' in document) ? ['tap'] : ['click'],
...
			for (var i = 0, itemsLength = items[length]; i < itemsLength; i++) {
				if (items[i][getElementsByTagName]('UL')[length]) {
					on(items[i], mouseHover[0], enterHandler);
					on(items[i], mouseHover[1], leaveHandler);
					on(items[i], mouseClick[0], leaveHandler);
```

**Comment by englishextra** [comment]
@thednp I ended up with [this](https://gist.github.com/englishextra/76206ce67897113f5520e31a766fc5ce), and I'm satisfied now. Thanks for your work. You had some interesting techniques in your code.

**Comment by englishextra** [comment]
@thednp here is the repo for you to test: https://github.com/englishextra/navbar.js

Works on Galaxy Tab Samsung / Desktop Windows 10

**Comment by thednp** [comment]
It's a bit more complicated than I would like but thanks nevertheless. Keep in mind that responsive design has just been featured recently with navbar.js, so some small details haven't been polished yet.

**Comment by thednp** [comment]
@englishextra please get ready to test the next version of navbar.js featuring ES6/ES7 scripting, rollup build tools, improved SCSS sources for faster render and mobile first design with responsive view special functions.

Currently testing and improving everything.

**Comment by thednp** [comment]
@englishextra please check the [roadmap](https://github.com/thednp/navbar.js/issues/9), you might like what it's all about.

Closing this down, future commit will solve this issue.

**Comment by thednp** [comment]
`npm install navbar.js`

**Comment by englishextra** [comment]
@thednp Thanks
