### ISSUE TITLE
is minifill required for ie11?

### ISSUE THREAD

**Issue by cekvenich** [thednp/navbar.js#7]
is minifill required for ie11 support?

**Comment by thednp** [comment]
It depends on your target market and your application.

**Comment by cekvenich** [comment]
I'm sorry, can I get just a bit more direction.
Is it needed for navbar support for ie 11 or not?

**Comment by thednp** [comment]
From what I can remember it's mainly for IE8+, but you can check for yourself to be sure. Download and check demo with and without minifill on IE11.

**Comment by cekvenich** [comment]
I did check and it worked in ie 11. Ps, I'm leveraging your code on www.ubaycap.com,   https://github.com/metabake and more. THANK YOU!
