### ISSUE TITLE
Bootstrap 4 support

### ISSUE THREAD

**Issue by silvioprog** [thednp/navbar.js#8]
Hello dudes, thanks for this awesome script!

So, I took a look at the Bootstrap example and it seems using the version 3. Do you have plans to support Bootstrap 4?

Thank you!

**Comment by thednp** [comment]
We're supporting V4 for a long time now.

**Comment by thednp** [comment]
We don't have any plans yet, but it should work fine with Bootstrap 4 with minor adjustments.

**Comment by silvioprog** [comment]
It would be very welcome. :-)
